### ISSUE TITLE
Addition of small test data 

### ISSUE THREAD

**Issue by amnahsiddiqa** [shuzhao-li-lab/PythonCentricPipelineForMetabolomics#15]
Josh it would be helpful to add a  small test dataset; you can upload it in compressed format on Figshare / Zonedo  or any other such platform easily. That would be very helpful to always try reproduce the issue or track it with a standard.

**Comment by jmmitc06** [comment]
There is now a command that will download the two test datasets from metabolomicss workbench. Downloading from there is slow, may move it in the future.
