### ISSUE TITLE
metadata field for a quick look at the group/class... during pcpfm run

### ISSUE THREAD

**Issue by gmhhope** [shuzhao-li-lab/PythonCentricPipelineForMetabolomics#51]
You need the metadata fields in the input files for that information and then you need to modify the call to the report function to color/marker by class. This use case is outside what is intended to be performed by the pipeline as it falls into the 'statistical analysis' portion of an analysis not raw feature table processing.

p.s. please open a new issue or discussion for off-topic threads. This will help us keep the issues clean.

_Originally posted by @jmmitc06 in https://github.com/shuzhao-li-lab/PythonCentricPipelineForMetabolomics/issues/49#issuecomment-1971621491_

**Comment by gmhhope** [comment]
So it is not handy to do that. Plz try give me a workable example command. I understand this is out of scope of the pipeline but I think it will probably very handy to do it. 

If not, yes, I can do it my own. This is just for improvement for users' experience. Again, you can pick it or drop it.

**Comment by jmmitc06** [comment]
This would require rerunning the analysis with a new sequence file as there is no way to inject the missing metadata into the object. 

If you did rerun it you could do something like `pcpfm report -i <experiment> --color_by='["genotype"]'` if genotype is the field on which you want to color the figures.

**Comment by jmmitc06** [comment]
Since this is outside the scope of the pipeline though, I'm inclined to close this issue. Use your output of choice and do the statistics in a separate notebook or script or metaboanalyst.
