### ISSUE TITLE
controlled vocabulary restriction for feature tables / empcpds

### ISSUE THREAD

**Issue by jmmitc06** [shuzhao-li-lab/PythonCentricPipelineForMetabolomics#63]
The reset command uses the moniker "*" as a signal to delete all but the asari tables and empcpds. While it is unlikely anyone would chose to name a feature table as '*' this is an edge case that should be addressed. 

The solution here is to have a parameter that is banned monikers that you are not allowed to save any monikered entity to. Could be in default_parameters

**Comment by gmhhope** [comment]
`reset` would deserve a small session to define the usage in your README.md at the root of the repo

**Comment by jmmitc06** [comment]
Thanks @gmhhope, this was added a while back but I forgot to close the issue.
