### ISSUE TITLE
scipy dependency in matchms

### ISSUE THREAD

**Issue by shuzhao-li** [shuzhao-li-lab/PythonCentricPipelineForMetabolomics#72]
I'm using matchms 0.27.0, which calls a deprecated function in scipy (1.14.0)
```
ImportError: cannot import name 'get_index_dtype' from 'scipy.sparse' 
```
I had to downgrade scipy to get through this:
```
pip install scipy==1.13.1
```

Maybe we should specify these versions in pcpfm install requirements.

**Comment by jmmitc06** [comment]
Looks like v1.14 was released less than a month ago, never noticed a deprecation warning. I like that workaround for the time being. I've added it to the main branch but still need to push to pypi.
