### ISSUE TITLE
Pcpfm output - annotation_table.tsv don't have feature's original m/z and adduct type assignment in the column

### ISSUE THREAD

**Issue by gmhhope** [shuzhao-li-lab/PythonCentricPipelineForMetabolomics#76]
[annotation_table_shortened_version.xlsx](https://github.com/user-attachments/files/17389030/annotation_table_shortened_version.xlsx)

I found out in pcpfm using the command: 

```bash
pcpfm build_empCpds -i /Users/gongm/Documents/projects/Adriana_HEU/main/repo_102723/script4metabo/2-pcpfm-run/data/pfmRun0905/HILICneg -tm full -em pref_for_analysis --add_singletons true
pcpfm l4_annotate -i /Users/gongm/Documents/projects/Adriana_HEU/main/repo_102723/script4metabo/2-pcpfm-run/data/pfmRun0905/HILICneg -em pref_for_analysis -nm pref_HMDB_LMSD_annotated_for_analysis
pcpfm generate_output -i /Users/gongm/Documents/projects/Adriana_HEU/main/repo_102723/script4metabo/2-pcpfm-run/data/pfmRun0905/HILICneg -em pref_HMDB_LMSD_annotated_for_analysis -tm pref_for_analysis
pcpfm report -i /Users/gongm/Documents/projects/Adriana_HEU/main/repo_102723/script4metabo/2-pcpfm-run/data/pfmRun0905/HILICneg --color_by='["batch"]' --marker_by='["Sample Type"]'
```

The annotation_table.tsv don't have columns that indicate how the annotation was assigned (e.g., original FID's m/z and most importantly the adduct form or any linked information that could expose the inference from m/z or the kiupu assigned ID or anything, this could be very confusing for people who don't know how to handle JSON and who are not familiar with how **kiupu** works, especially that is a very big JSON file in the `pref_HMDB_LMSD_annotated_for_analysis_empCpds.json`. So it is probably better to have an intermediate JSON file (better a table), if there isn't, that could get people a hint at how the assignment was achieved. Even though this is L4 annotation, those information could be extremely important and useful for checking any metabolites of interest that jump out in the initial annotation. 

```bash
.
├── annotation_table.tsv #  This file
├── experiment.json
├── feature_table.tsv
├── pref_HMDB_LMSD_annotated_for_analysis_empCpds.json # This file is super big and probably better to get an intermediate file (e.g., tsv or json file) out for quick check.
├── pref_for_analysis_Feature_table.tsv
├── renamed
├── report.pdf
└── sample_annot_table.tsv
```

<img width="1304" alt="Screenshot 2024-10-16 at 12 19 22 AM" src="https://github.com/user-attachments/assets/e3de6a56-b20a-43d5-903f-d01dc82294b8">

**Comment by gmhhope** [comment]
The annotation table should be self-sufficient, providing all the necessary bridging information, including the original m/z, adduct type, and kiupu ID. Without this, the table risks becoming confusing for biologists and chemists unfamiliar with the annotation process or the structure of the JSON file. These users should not need to dive into the JSON or complex procedures to understand how the assignments were made. Including this information directly in the table ensures that it remains informative and minimizes the risk of misunderstandings and running in caveat.

**Comment by jmmitc06** [comment]
Lets talk more about this in-person. While I agree in principle with what you are wanting, there is a reason why we didn't make a single table as you described. I also hesitate to generalize your experience to everyone since others have appreciated that the output tables are not exhaustive. For some users for instance, having a massive table with a lot of unnecessary data, may lead to more problems than leaving the deep dive to the more computationally oriented users. So we need to decide what a low-tech user needs rather than giving them everything.

**Comment by jmmitc06** [comment]
Minghao, take a look at V1.1.1 on github. I added an option called "comprehensive_output" to the generate_output command. When true, the annotation table will include all the feature information as well. This of course, duplicates the feature table in the annotation table, but it does give you the information you want.

**Comment by jmmitc06** [comment]
I'm going to close this issue since I believe I have solved the problem. I indicated your contribution in the version log. Feel free to open this issue or another issue for other feature requests or continued development on this issue. Thanks!
