### ISSUE TITLE
can you provide an example file for sequence.csv ?

### ISSUE THREAD

**Issue by pickyseok** [shuzhao-li-lab/PythonCentricPipelineForMetabolomics#79]
**Is your feature request related to a problem? Please describe.**
I made my_sequence.csv manually but i can't assemble the sequence file and aquisition files.
Here is my sequence file. [metadata.csv](https://github.com/user-attachments/files/17903944/metadata.csv)

The error message is following:
```
Attempting:  assemble
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Skipping:  None  no acquisition data found
Unable to create empty experiment
```

Why this file doesn't work ?

**Comment by jmmitc06** [comment]
Thanks for raising the issue. The sequence sheet is a pain point with the current pipeline and future versions will have something more user friendly.

 I think the issue with the file you provided, assuming that the paths are correct (I can't check that, but if you are on windows the path seems reasonable), is that the default column name for the filepath should be 'Filepath' not 'Path'. 

You can workaround that by adding this to the assemble command: 

`--name_field='Name' --path_field='Path'`

The Name field should be fine, but the above addition to the assemble command will remove any ambiguity. 

Let me know if this does not work for you and I can look closer.

**Comment by pickyseok** [comment]
Thanks for a quick response ! 

As you mentioned, i am now using WSL2 in windows OS and the path is correct. 
Unfortunately, i added the parameters for the name_field and path field to the assemble command but it keeps getting an error message (Permission Error [WinError 32]:experiment.json.tmp). **And I don't know the exact reason, but when I run the script in Ubuntu from WSL2, the problem is solved.** There may have been a dependency issue when installing the pcpfm package using pip on WSL2. Thanks again about your kind comments.

**Comment by jmmitc06** [comment]
No problem. I don't have much experience with WSL but if it is anything like other containerization / virtualization technologies, there could be nonsense going on with accessing files that, to the perspective of WSL, reside on a different machine or file system.

I'll open an issue to test issues with WSL, it should work, but since we have a workaround, it won't be a priority.
